services:
  library:
    build: library/
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - counter
    command: npm run start
  counter:
    build: counter/
    ports:
      - 81:3001
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./counter/data:/app/data
    command: npm run start
